// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Data.Entities;

public partial class EmployeeSalary
{
    public int? EmpId { get; set; }

    public string EmpName { get; set; }
}